accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

from django import forms
from . import views
from . import forms

from django.conf.urls.static import static
from myproject import settings


urlpatterns = [
    path('login/', auth_views.LoginView.as_view(next_page= reverse_lazy("home"),template_name= 'accounts/login.html', authentication_form= forms.CustomAuthenticationForm, redirect_authenticated_user= True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page="/login"), name='logout'),
    path('change-password/', views.change_password, name='change_password'),
    path('profile/', views.profile_view, name='profile_view'),
]

myproject/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include, reverse_lazy
from django.views.generic import TemplateView
from django.shortcuts import render
from django.forms import ModelForm
from django.conf.urls.static import static
from myproject import settings
from django.views.generic import CreateView, RedirectView
from officers_affairs import models, views
from django.http import HttpResponse
import json

import cv2
from rembg import remove
import numpy as np
import os


def testView(request):
    return render(request, "test.html")

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('test/', testView),
    path('officers_affairs/', include('officers_affairs.urls')),
    path('', RedirectView.as_view(url=reverse_lazy("home"))),
    path('about/', views.about, name='about'),
    
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

officers_affairs/urls.py
from django.urls import path
from django.views import generic
from . import views
from . import models
from django.conf.urls.static import static
from myproject import settings

urlpatterns = [
    path('officers_home/', views.officers_home_view, name='home'),
    path('officers/', views.officers_view, name='officers'),
    # path('delete_officers/', views.officers_delete_view, name='delete'),
    # path('update_officers/', views.officers_update_view, name='update'),
    # Fragments
    path('officers_list/', views.officers_list, name="officers_list"),
    path('partial_officers/', views.partial_officers, name="partial_officers"),
    path('officers_add/', views.officers_add, name="officers_add" ),
    path('officers_add/<int:pk>', views.officers_add, name="officers_add" ),
    path('officers_delete/<int:pk>', views.officers_delete.as_view(), name="officers_delete" ),
    path('officer/<int:pk>/', views.officer_detail, name='officer_detail'),
    
    path('leave/create/', views.create_update_leave_request, name='create_leave_request'),
    path('leave/update/<int:pk>', views.create_update_leave_request, name='update_leave_request'),
    path('leave/requests/', views.leave_requests_list, name='leave_requests_list'),  # For leaders to see all requests
    path('leave/my-requests/', views.leave_requests, name='leave_requests'),  # For users to see only their requests
    path('leave/approve/<int:pk>/', views.approve_leave_request, name='approve_leave_request'),
    path('delete-leave-request/<int:pk>/', views.delete_leave_request, name='delete_leave_request'),
    # path('calculate-leave-remaining/', views.calculate_leave_remaining, name='calculate_leave_remaining'),
    
    path('notifications/', views.notifications_view, name='notifications'),
    path('notifications/mark_read/<int:notification_id>/', views.mark_notification_read, name='mark_notification_read'),
    path('notifications/check-new/', views.check_new_notifications, name='check_new_notifications'),
    
    path('notification_list/', views.notification_list, name='notification_list'),
    
    path('record_attendance/', views.record_attendance, name='record_attendance'),
    path('attendance_list/', views.attendance_list, name='attendance_list'),
    
    path('record_parade_attendance/', views.record_parade_attendance, name='record_parade_attendance'),
    path('parade_attendance_list/', views.parade_attendance_list, name='parade_attendance_list'),

    
    path('shifts/assign/', views.assign_shifts, name='assign_shifts'),
    path('shifts/list/', views.shifts_list, name='shifts_list'),
    path('shifts/my-requests', views.my_shift_swap_requests, name='my-shift-swap-requests'),
    path('shifts/swap-requests', views.shift_swap_requests_list, name='shift_swap_requests_list'),
    path('shifts/swap/<int:original_shift_id>/<int:new_shift_id>/', views.shift_swap, name='shift_swap'),
    path('shifts/swap/approve_shift_request/<int:shift_id>', views.approve_shift_request, name='approve_shift_request'),



    path('officer-gate-log/', views.officer_gate_log, name='officer_gate_log'),
    path('visitor-log/', views.visitor_log, name='visitor_log'),
    path('daily-log/', views.daily_log_view, name='daily_log_view'),

    
]

officers_affairs/models.py
# models.py
from django.db import models
from django.contrib.auth.models import User,Group
from django.core.validators import MinLengthValidator
from django.utils.translation import gettext_lazy as _
from django.utils import timezone





class Rank(models.Model):
    
    name = models.CharField(max_length=100, unique=True,verbose_name="الرتبه")
    image = models.ImageField(upload_to='ranks/', null=True, blank=True,verbose_name="")
    def __str__(self):
        return self.name

class BloodType(models.Model):
    type = models.CharField(max_length=10, unique=True)

    def __str__(self):
        return self.type

class Weapon(models.Model):
    name = models.CharField(max_length=100, unique=True,verbose_name="الســلاح")

    def __str__(self):
        return self.name

class Unit(models.Model):
    name = models.CharField(max_length=100, unique=True,verbose_name="الــوحدة")

    def __str__(self):
        return self.name


class Section(models.Model):
    name = models.CharField(max_length=100, unique=True,verbose_name="الـقسم")
    branch = models.ForeignKey(Group, on_delete=models.CASCADE, null=True, blank=True, related_name='sections',verbose_name="الـفرع")
    def __str__(self):
        return self.name

class Job(models.Model):
    name = models.CharField(max_length=100, unique=True,verbose_name="الوظيفه")
    section = models.ForeignKey(Section, on_delete=models.CASCADE, null=True, blank=True, related_name='jobs',verbose_name="القسم")
    def __str__(self):
        return self.name




class UnitStatus(models.Model):
    name = models.CharField(max_length=100, unique=True, verbose_name=" حالة الضابط بالوحدة")

    def __str__(self):
        return self.name
    
    
class MaritalStatus(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name

class OfficerStatus(models.Model):
    name = models.CharField(max_length=100, unique=True, verbose_name="حالة الضابط")

    def __str__(self):
        return self.name



class Officer(models.Model):
    
    ROLE_CHOICES = [
        ('المدير', 'المدير'),
        ('رئيس فرع شئون ضباط', 'رئيس فرع شئون ضباط'),
        ('نائب المدير', 'نائب المدير'),
        ('رئيس فرع السكرتارية', 'رئيس فرع السكرتارية'),
    ]
    
    is_leader = models.BooleanField(default=False, verbose_name="قائد الفرع")
    role = models.CharField(max_length=50, choices=ROLE_CHOICES, null=True, blank=True, verbose_name="الوظيفة الادارية")
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='officer_profile', null=True,blank=True)
    full_name = models.CharField(max_length=255, verbose_name="اسم الضابط")
    rank = models.ForeignKey(Rank, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="الرتبة")
    military_number = models.CharField(max_length=50, unique=True, verbose_name="الرقم العسكري")
    seniority_number = models.CharField(max_length=50, verbose_name="رقم الاقدمية")
    national_id = models.CharField(
        max_length=14,
        validators=[MinLengthValidator(14)],
        blank=True,
        null=True,
        verbose_name="الرقم القومي"
    )
    blood_type = models.ForeignKey(BloodType, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="فصيلة الدم")
    weapon = models.ForeignKey(Weapon, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="السلاح")
    phone1 = models.CharField(max_length=15, verbose_name="رقم الهاتف ١")
    phone2 = models.CharField(max_length=15, blank=True, null=True, verbose_name= "رقم الهاتف ٢")
    home_phone = models.CharField(max_length=15, blank=True, null=True, verbose_name="رقم هاتف المنزل")
    marital_status = models.ForeignKey(MaritalStatus, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="الحالة الإجتماعية")
    address = models.CharField(max_length=255,verbose_name="العنوان")
    profile_image = models.ImageField(upload_to='officers/', null=True, blank=True, verbose_name="الصورة الشخصية")
    birth_date = models.DateField(blank=True, null=True, verbose_name="تاريخ الميلاد")
    unit = models.ForeignKey(Unit, on_delete=models.SET_NULL, null=True, blank=True, related_name='current_unit', verbose_name="الوحدة")
    join_date = models.DateField(blank=True, null=True, verbose_name="تاريخ الضم")
    previous_unit = models.ForeignKey(Unit, on_delete=models.SET_NULL, null=True, blank=True, related_name='previous_units', verbose_name="الوحدة السابقة")
    status = models.ForeignKey(OfficerStatus, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="الحالة")
    unit_status = models.ForeignKey(UnitStatus, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="الحالة بالوحدة")
    branch = models.ForeignKey(Group, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="الفرع")
    section = models.ForeignKey(Section, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="القسم")
    job = models.ForeignKey(Job, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="الوظيفه")
    batch_number = models.CharField(max_length=40, blank=True, null=True, verbose_name="رقم الدفعة")
    rank_promotion_date = models.DateField(blank=True, null=True, verbose_name="تاريخ آخر ترقي")
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='created_officers')
    updated_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='updated_officers')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    

    def __str__(self):
        return self.full_name
    
    
#جدول طلبات الأجازة

class LeaveRequest(models.Model):
    ANNUAL_LEAVE = 'annual'
    CASUAL_LEAVE = 'casual'
    LEADER_GRANT = 'leader_grant'
    INSTEAD_OF_REST = 'instead_of_rest'
    REST = 'rest'
    
    LEAVE_TYPES = [
        (ANNUAL_LEAVE, "سنوية"),
        (CASUAL_LEAVE, "عارضة"),
        (LEADER_GRANT, "منحة قائد"),
        (INSTEAD_OF_REST, "بدل راحة"),
        (REST, " راحة"),
    ]
    
    PENDING = 'pending'
    APPROVED = 'approved'
    REJECTED = 'rejected'
    
    STATUS_CHOICES = [
        (PENDING, 'جـاري التصديــق'),
        (APPROVED, 'تصــدق'),
        (REJECTED, 'لم يتصدق'),
    ]
    
    officer = models.ForeignKey(Officer, on_delete=models.CASCADE, related_name='leave_requests', verbose_name="الضابط")
    approver = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL, verbose_name="المصدق الحالي")
    final_approver = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='final_approver', verbose_name="المصدق النهائي")
    leave_type = models.CharField(max_length=20, choices=LEAVE_TYPES, verbose_name="نوع الإجازة")
    start_date = models.DateField(verbose_name="تاريخ بداية الإجازة")
    end_date = models.DateField(verbose_name="تاريخ انتهاء الإجازة")
    reason = models.TextField(blank=True, verbose_name="السبب")
    status = models.CharField(max_length=200, choices=STATUS_CHOICES, default=PENDING, verbose_name="الحالة")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء")
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='created_leave_request')
    days_taken = models.PositiveIntegerField(default=0, verbose_name="عدد الأيام المأخوذة")
    remaining_days = models.IntegerField(null=True, blank=True ,  verbose_name="عدد الأيام المتبقية")  # الأيام المتبقية
    compensation_date = models.DateField(null=True, blank=True, verbose_name="بدل عن ترايخ")


    def save(self, *args, **kwargs):
        if self.start_date and self.end_date:
            self.days_taken = (self.end_date - self.start_date).days + 1  # +1 لحساب اليوم الأول
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.officer.user.username} - {self.get_leave_type_display()}"


class Notification(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.TextField()
    is_read = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    link = models.URLField(blank=True, null=True)  # Add a link field for redirection

    def __str__(self):
        return self.message
    
    
class DailyAttendance(models.Model):
    officer = models.ForeignKey(Officer, on_delete=models.CASCADE, verbose_name="الضابط")
    date = models.DateField(default=timezone.now, verbose_name="التاريخ")
    status = models.ForeignKey(UnitStatus, on_delete=models.SET_NULL, null=True, verbose_name="الحالة اليومية")
    notes = models.TextField(blank=True, null=True, verbose_name="ملاحظات")

    class Meta:
        unique_together = ('officer', 'date')
        verbose_name = 'تمام يومي'
        verbose_name_plural = 'تمامات يومية'

    def __str__(self):
        return f"{self.officer.full_name} - {self.date} - {self.status.name}"  
    
# نوبطجيات 


class ShiftTeam(models.Model):
    TEAM_TYPE_CHOICES = [
        ('قائد منوب', 'قائد منوب'),
        ('ضابط نوبطچي', 'ضابط نوبطچي')
    ]
    team_type = models.CharField(max_length=20, choices=TEAM_TYPE_CHOICES, verbose_name="نوع الطاقم")
    officer = models.ForeignKey(Officer, on_delete=models.CASCADE, related_name='shift_teams', verbose_name="الضابط")
    created_at = models.DateTimeField(auto_now_add=True,verbose_name="تاريخ الإنشاء")


class Shift(models.Model):
    officer = models.ForeignKey(Officer, on_delete=models.CASCADE)
    team = models.ForeignKey(ShiftTeam, on_delete=models.CASCADE)
    start_date = models.DateField()
    end_date = models.DateField()
    is_holiday = models.BooleanField(default=False)


class ShiftSwapRequest(models.Model):
    PENDING = 'pending'
    APPROVED = 'approved'
    REJECTED = 'rejected'
    
    STATUS_CHOICES = [
        (PENDING, 'جـاري التصديــق'),
        (APPROVED, 'تصــدق'),
        (REJECTED, 'لم يتصدق'),
    ]

templates/officers_affairs/addOfficer.html
{% load django_bootstrap5 %} 

<form hx-post="{{ request.path }}" class="modal-content" hx-headers='{"X-CSRFToken":"{{ csrf_token }}"}' hx-encoding="multipart/form-data">
    <div class="modal-header">
      <h5 class="modal-title">اضافة ضابط</h5>
      <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
      </button>
    </div>

    <div class="modal-body">
        {% bootstrap_form form %}
    </div>

    <div class="modal-footer">
      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">إغلاق</button>
      <button type="submit" class="btn btn-primary">اضافة</button>
    </div>
</form>

templates/officers_affairs/error.html
<!DOCTYPE html>
<html lang="ar">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Error</title>
</head>
<body>
    <h1>خطأ</h1>
    <p>{{ error_message }}</p>
    <a href="{% url 'leave_requests_list' %}">العودة إلى قائمة الطلبات</a>
</body>
</html>

templates/officers_affairs/notification_list.html
{% load custom_filters %}
{% for notification in notifications %}
<li>
    <a id="notification-{{notification.id}}" class="dropdown-item notification-item d-flex" data-id="{{ notification.id }}" data-link="{{ notification.link }}" href="#">
            {{ notification.message }}
            <small class="text-muted">{{ notification.created_at|date:"d-m-Y سعت  Hi "|arabic_numbers }}</small>
        </a>
    </li>
{% empty %}
    <li><a class="dropdown-item" href="#">لا توجد إشعارات</a></li>
{% endfor %}

templates/officers_affairs/notifications.html
{% extends "base.html" %}

{% block content %}
    <h1>Notifications</h1>
    <ul>
        {% for notification in notifications %}
            <li>
                <strong>{{ notification.created_at }}</strong>: {{ notification.message }}
                {% if not notification.is_read %}
                    <em>(Unread)</em>
                {% endif %}
            </li>
        {% empty %}
            <li>No notifications.</li>
        {% endfor %}
    </ul>
{% endblock %}

templates/officers_affairs/officer_confirm_delete.html
<form hx-post="{{ request.path }}" class="modal-content" hx-headers='{"X-CSRFToken":"{{ csrf_token }}"}'>
    <div class="modal-header">
      <h5 class="modal-title">حذف ضابط</h5>
      <button type="button" class="close" style="margin-right:auto" data-bs-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
      </button>
    </div>

    <div class="modal-body">
      <p class="p-1"> هل تريد حقاً حذف الضابط ؟ {{ officer.full_name }}</p>
      
    </div>

    <div class="modal-footer">
      <button type="submit"  class="btn btn-danger">حذف</button>
      <button type="button"  class="btn btn-success" data-bs-dismiss="modal">تراجع</button>
    </div>
</form>

templates/officers_affairs/officer_list.html
{% load static %}
{% load django_bootstrap5 %}
{% load custom_filters %}
<div id="officers_list"
     hx-trigger="officer_list_changed from:body"
     hx-get="{% url 'officers_list' %}"
     hx-vals="js:{...getCurrentUrlParams()}"
     hx-target="this">
  <form hx-get="{% url "officers_list" %}"
        hx-target="#officers_list"
        hx-swap='outerHTML'
        id="filterForm"
        class="mb-3">
    <!-- Rank Filter buttons -->
    <div class="btn-group-sm"
         role="group"
         aria-label="Basic radio toggle button group">
      <input type="radio"
             class="btn-check"
             id="rank-null"
             autocomplete="off"
             {% if officers_filter.form.rank.value == None %}checked{% endif %}
             hx-on:click="this.closest('form').querySelector('[name=rank]').disabled=true; this.closest('form').querySelector('[name=rank]').value = undefined; document.getElementById('filterSubmitBtn').click()">
      <label class="btn btn-outline-secondary" for="rank-null">الكل</label>
      {% for rank in ranks %}
        <input type="radio"
               class="btn-check"
               id="rank-{{ rank.id }}"
               autocomplete="off"
               {% if officers_filter.form.rank.value == rank.id|to_string %}checked{% endif %}
               hx-on:click="this.closest('form').querySelector('[name=rank]').disabled=false; this.closest('form').querySelector('[name=rank]').value = {{ rank.id }}; document.getElementById('filterSubmitBtn').click()">
        <label class="btn btn-outline-primary dark-mode" for="rank-{{ rank.id }}">{{ rank.name }}</label>
      {% endfor %}
    </div>
    <div class="collapse" id="collapseFilter">
      <div class="card card-body">
        {% for field in officers_filter.form.visible_fields %}
          <div class="form-group mb-2">
            <label style="margin-left: 1rem;">
              <input type="checkbox" class="filter-toggle" data-filter="{{ field.name }}">
            </label>
            <label>{{ field.label }}</label>
            {{ field }}
            {% for error in field.errors %}<span class="help-block text-danger">{{ error }}</span>{% endfor %}
          </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary shadow" id="filterSubmitBtn">بحث</button>
      </div>
    </div>
  </form>
  <!-- Officers List -->
  <div class="row">
    {% for officer in officers_filter.qs %}
      {% if perms.officers_affairs.view_officer %}
        <!-- Officer Card -->
        <div class="col-md-4 mb-4">
          <div class="card card-widget widget-user">
            <!-- Officer Card Dropdown (if permitted) -->
            {% if perms.officers_affairs.change_officer or perms.officers_affairs.delete_officer %}
              <div class="position-absolute top-0 end-0">
                <button type="button"
                        class="btn dropdown-toggle btn-outline-secondary"
                        data-bs-toggle="dropdown">
                  <span class="sr-only">Toggle Dropdown</span>
                </button>
                <ul class="dropdown-menu">
                  {% if perms.officers_affairs.change_officer %}
                    <li>
                      <a class="dropdown-item edit-item"
                         hx-get="{% url 'officers_add' pk=officer.pk %}"
                         hx-target="#dialog">تعديل</a>
                    </li>
                  {% endif %}
                  {% if perms.officers_affairs.delete_officer %}
                    <li>
                      <a class="dropdown-item delete-item"
                         hx-get="{% url 'officers_delete' pk=officer.pk %}"
                         hx-target="#dialog">حذف</a>
                    </li>
                  {% endif %}
                </ul>
              </div>
            {% endif %}
            <!-- Officer Header with Rank -->
            {% if officer.rank.image %}
              <div class="widget-user-header text-white"
                   style="background-image: url('{{ officer.rank.image.url }}');
                          background-size: cover">
              {% else %}
                <div class="widget-user-header text-white"
                     style="background-image: url('{{ officer.rank }}');
                            background-size: cover">
                {% endif %}
                <h3 class="widget-user-username">{{ officer.rank.name }}</h3>
                <h4 class="widget-user-desc" style="text-shadow:1px 1px black">{{ officer.full_name }}</h4>
              </div>
              <a href="{% url 'officer_detail' officer.pk %}">
                <!-- Officer Image -->
                <div class="widget-user-image">
                  {% if officer.profile_image %}
                    <img class="rounded-circle elevation-2"
                         style="width:100px;
                                height:100px;
                                box-shadow:0 3px 6px rgba(0,0,0,.16),0 3px 6px rgba(0,0,0,.23)!important"
                         src="{{ officer.profile_image.url }}"
                         alt="Officer Image">
                  {% else %}
                    <img class="rounded-circle elevation-2"
                         style="width:100px;
                                height:100px;
                                box-shadow:0 3px 6px rgba(0,0,0,.16),0 3px 6px rgba(0,0,0,.23)!important"
                         src="{% static 'images/user-avatar.png' %}"
                         alt="User Avatar">
                  {% endif %}
                </div>
              </a>
              <!-- Officer Details -->
              <div class="card-body">
                <div class="text-end mt-5">
                  <h5 class="description-header">الرقم العسكري: {{ officer.military_number|arabic_numbers }}</h5>
                  <h5 class="description-header">رقم الاقدمية: {{ officer.seniority_number|arabic_numbers }}</h5>
                  <h5 class="description-header">الفرع: {{ officer.branch.name|default:"لايوجد" }}</h5>
                  {% comment %} <h5 class="description-header">القسم: {{ officer.section.name }}</h5> {% endcomment %}
                  <h5 class="description-header">السلاح: {{ officer.weapon.name }}</h5>
                  <h5 class="description-header">رقم الهاتف: {{ officer.phone1|arabic_numbers}}</h5>
                  {% comment %}
                    <h5 class="description-header">الوظيفة: {{ officer.job.name }}</h5>
                   <h5 class="description-header">الوحدة: {{ officer.unit.name }}</h5>
                  {% if officer.phone2 %}<h5 class="description-header">رقم الهاتف 2: {{ officer.phone2 }}</h5>{% endif %}
                  {% if officer.home_phone %}<h5 class="description-header">رقم الهاتف المنزلي: {{ officer.home_phone }}</h5>{% endif %} 
                  {% endcomment %}
                </div>
              </div>
              <a href="{% url 'officer_detail' officer.pk %}"
                 class="card-footer text-center link-primary link-underline-opacity-0 link-underline-opacity-50-hover fw-bold ">المزيـــد</a>
            </div>
          </div>
        {% endif %}
      {% empty %}
        <h3>لايوجد</h3>
      {% endfor %}
    </div>

</div>
<script>
 document.getElementById('filterForm').addEventListener('submit', function(event) {
      event.preventDefault();  // Prevent the default form submission

      console.log("filter form submit");
      
      // Serialize the form data
      const form = event.target;
      const formData = new FormData(form);
      const searchParams = new URLSearchParams(formData).toString();

      // Update the URL without reloading the page
      const newUrl = `${window.location.pathname}?${searchParams}`;
      history.pushState(null, '', newUrl);  // Update the URL

      // Temporarily remove the event listener to prevent an infinite loop
      form.removeEventListener('submit', arguments.callee);

      // Trigger the HTMX request manually
      htmx.trigger(form, 'submit');
    });




  function getCurrentUrlParams() {
        const params = new URLSearchParams(window.location.search);
        let paramObj = {};
        params.forEach((value, key) => {
            paramObj[key] = value;
        });
        return paramObj;  
    }


  </script>

templates/officers_affairs/partial_officers.html
{% load django_bootstrap5 %}
{% load custom_filters %}
{% load static %}

<div class="row" id="partial_officers" hx-trigger="officer_list_changed from:body" hx-get="{% url 'partial_officers' %}" hx-target="this"></div>
 <!-- Main content -->
 <section class="content">                  
    <!-- Default box -->
    <div class="card card-solid">
      <div class="card-body pb-0">
        <div class="row d-flex ">
        <div class="row" id="partial_officers" hx-trigger="officer_list_changed from:body" hx-get="{% url 'partial_officers' %}" hx-target="this"></div>
        {% for officer in officers %}
          <!-- بداية الضابط -->
          <div   class="col-12 col-sm-6 col-md-4 d-flex  ">
            <div  id="" class="card w-100 mb-4">
              <div  class="card-header text-muted border-bottom-0 shadow">
                {{officer.rank}}
              </div>
              <div class="card-body pt-0">
                <div class="row">
                  <div class="col-7">
                    <h2 class="lead text-right"><b>{{ officer.full_name }}</b></h2>
                    <ul class="fa-ul text-muted text-right">
                      <li class="small"><span class="fa-li"></span>الحالة: {{ officer.unit_status|default:"غير معروفة" }}</li>
                      <li class="small"><span class="fa-li"></span>{{ officer.get_status_display }}</li>
                    </ul>

                  </div>
         
                  <div class="col-5 text-center">
                  {% if officer.profile_image %}
                  <img class="img-circle elevation-2 img-fluid" src="{{ officer.profile_image.url }}" style="max-width: 100px; max-height: 100px;" alt="Officer Image">
                  {% else %}
                    <img class="img-circle elevation-2 img-fluid" src="{% static 'images/user-avatar.png' %}" style="max-width: 100px; max-height: 100px;" alt="">
  
                  {% endif %}
                      
                  </div>
                </div>
              </div>
              {% if perms.officers_affairs.change_officer or perms.officers_affairs.delete_officer %}
              <div class="card-footer">
                <div class="text-right">
                  {% if perms.officers_affairs.delete_officer %}
                  <a hx-get="{% url 'officers_delete' pk=officer.pk %}" hx-target="#dialog"  class="btn btn-sm bg-danger">
                    <i class="fas fa-trash"></i> حذف
                  </a>
                  {% endif %}
                  {% if perms.officers_affairs.change_officer %}
                  <a hx-get="{% url 'officers_add' pk=officer.pk %}" hx-target="#dialog" class="btn btn-sm btn-primary">
                    <i class="fas fa-book"></i> تعديل
                  </a>
                  {% endif %}
                </div>
              </div>
              {% endif %}
            </div>
            
          </div>
           <!-- نهاية الكتاب -->
        {% endfor %}
        </div>
        
      </div>
      <!-- /.card-body -->

      <!-- /.card-footer -->
    </div>
    <!-- /.card -->


  </section>
  <!-- /.content -->