accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

from django import forms
from . import views
from . import forms

from django.conf.urls.static import static
from myproject import settings


urlpatterns = [
    path('login/', auth_views.LoginView.as_view(next_page= reverse_lazy("home"),template_name= 'accounts/login.html', authentication_form= forms.CustomAuthenticationForm, redirect_authenticated_user= True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page="/login"), name='logout'),
    path('change-password/', views.change_password, name='change_password'),
    path('profile/', views.profile_view, name='profile_view'),
]

myproject/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include, reverse_lazy
from django.views.generic import TemplateView
from django.shortcuts import render
from django.forms import ModelForm
from django.conf.urls.static import static
from myproject import settings
from django.views.generic import CreateView, RedirectView
from officers_affairs import models, views
from django.http import HttpResponse
import json

import cv2
from rembg import remove
import numpy as np
import os


def testView(request):
    return render(request, "test.html")

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('test/', testView),
    path('officers_affairs/', include('officers_affairs.urls')),
    path('', RedirectView.as_view(url=reverse_lazy("home"))),
    path('about/', views.about, name='about'),
    
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

officers_affairs/models.py
# models.py
from django.db import models
from django.contrib.auth.models import User,Group
from django.core.validators import MinLengthValidator
from django.utils.translation import gettext_lazy as _
from django.utils import timezone





class Rank(models.Model):
    
    name = models.CharField(max_length=100, unique=True,verbose_name="الرتبه")
    image = models.ImageField(upload_to='ranks/', null=True, blank=True,verbose_name="")
    def __str__(self):
        return self.name

class BloodType(models.Model):
    type = models.CharField(max_length=10, unique=True)

    def __str__(self):
        return self.type

class Weapon(models.Model):
    name = models.CharField(max_length=100, unique=True,verbose_name="الســلاح")

    def __str__(self):
        return self.name

class Unit(models.Model):
    name = models.CharField(max_length=100, unique=True,verbose_name="الــوحدة")

    def __str__(self):
        return self.name


class Section(models.Model):
    name = models.CharField(max_length=100, unique=True,verbose_name="الـقسم")
    branch = models.ForeignKey(Group, on_delete=models.CASCADE, null=True, blank=True, related_name='sections',verbose_name="الـفرع")
    def __str__(self):
        return self.name

class Job(models.Model):
    name = models.CharField(max_length=100, unique=True,verbose_name="الوظيفه")
    section = models.ForeignKey(Section, on_delete=models.CASCADE, null=True, blank=True, related_name='jobs',verbose_name="القسم")
    def __str__(self):
        return self.name




class UnitStatus(models.Model):
    name = models.CharField(max_length=100, unique=True, verbose_name=" حالة الضابط بالوحدة")

    def __str__(self):
        return self.name
    
    
class MaritalStatus(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name

class OfficerStatus(models.Model):
    name = models.CharField(max_length=100, unique=True, verbose_name="حالة الضابط")

    def __str__(self):
        return self.name



class Officer(models.Model):
    
    ROLE_CHOICES = [
        ('المدير', 'المدير'),
        ('رئيس فرع شئون ضباط', 'رئيس فرع شئون ضباط'),
        ('نائب المدير', 'نائب المدير'),
        ('رئيس فرع السكرتارية', 'رئيس فرع السكرتارية'),
    ]
    
    is_leader = models.BooleanField(default=False, verbose_name="قائد الفرع")
    role = models.CharField(max_length=50, choices=ROLE_CHOICES, null=True, blank=True, verbose_name="الوظيفة الادارية")
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='officer_profile', null=True,blank=True)
    full_name = models.CharField(max_length=255, verbose_name="اسم الضابط")
    rank = models.ForeignKey(Rank, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="الرتبة")
    military_number = models.CharField(max_length=50, unique=True, verbose_name="الرقم العسكري")
    seniority_number = models.CharField(max_length=50, verbose_name="رقم الاقدمية")
    national_id = models.CharField(
        max_length=14,
        validators=[MinLengthValidator(14)],
        blank=True,
        null=True,
        verbose_name="الرقم القومي"
    )
    blood_type = models.ForeignKey(BloodType, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="فصيلة الدم")
    weapon = models.ForeignKey(Weapon, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="السلاح")
    phone1 = models.CharField(max_length=15, verbose_name="رقم الهاتف ١")
    phone2 = models.CharField(max_length=15, blank=True, null=True, verbose_name= "رقم الهاتف ٢")
    home_phone = models.CharField(max_length=15, blank=True, null=True, verbose_name="رقم هاتف المنزل")
    marital_status = models.ForeignKey(MaritalStatus, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="الحالة الإجتماعية")
    address = models.CharField(max_length=255,verbose_name="العنوان")
    profile_image = models.ImageField(upload_to='officers/', null=True, blank=True, verbose_name="الصورة الشخصية")
    birth_date = models.DateField(blank=True, null=True, verbose_name="تاريخ الميلاد")
    unit = models.ForeignKey(Unit, on_delete=models.SET_NULL, null=True, blank=True, related_name='current_unit', verbose_name="الوحدة")
    join_date = models.DateField(blank=True, null=True, verbose_name="تاريخ الضم")
    previous_unit = models.ForeignKey(Unit, on_delete=models.SET_NULL, null=True, blank=True, related_name='previous_units', verbose_name="الوحدة السابقة")
    status = models.ForeignKey(OfficerStatus, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="الحالة")
    unit_status = models.ForeignKey(UnitStatus, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="الحالة بالوحدة")
    branch = models.ForeignKey(Group, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="الفرع")
    section = models.ForeignKey(Section, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="القسم")
    job = models.ForeignKey(Job, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="الوظيفه")
    batch_number = models.CharField(max_length=40, blank=True, null=True, verbose_name="رقم الدفعة")
    rank_promotion_date = models.DateField(blank=True, null=True, verbose_name="تاريخ آخر ترقي")
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='created_officers')
    updated_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='updated_officers')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    

    def __str__(self):
        return self.full_name
    
    
#جدول طلبات الأجازة

class LeaveRequest(models.Model):
    ANNUAL_LEAVE = 'annual'
    CASUAL_LEAVE = 'casual'
    LEADER_GRANT = 'leader_grant'
    INSTEAD_OF_REST = 'instead_of_rest'
    REST = 'rest'
    
    LEAVE_TYPES = [
        (ANNUAL_LEAVE, "سنوية"),
        (CASUAL_LEAVE, "عارضة"),
        (LEADER_GRANT, "منحة قائد"),
        (INSTEAD_OF_REST, "بدل راحة"),
        (REST, " راحة"),
    ]
    
    PENDING = 'pending'
    APPROVED = 'approved'
    REJECTED = 'rejected'
    
    STATUS_CHOICES = [
        (PENDING, 'جـاري التصديــق'),
        (APPROVED, 'تصــدق'),
        (REJECTED, 'لم يتصدق'),
    ]
    
    officer = models.ForeignKey(Officer, on_delete=models.CASCADE, related_name='leave_requests', verbose_name="الضابط")
    approver = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL, verbose_name="المصدق الحالي")
    final_approver = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='final_approver', verbose_name="المصدق النهائي")
    leave_type = models.CharField(max_length=20, choices=LEAVE_TYPES, verbose_name="نوع الإجازة")
    start_date = models.DateField(verbose_name="تاريخ بداية الإجازة")
    end_date = models.DateField(verbose_name="تاريخ انتهاء الإجازة")
    reason = models.TextField(blank=True, verbose_name="السبب")
    status = models.CharField(max_length=200, choices=STATUS_CHOICES, default=PENDING, verbose_name="الحالة")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء")
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='created_leave_request')
    days_taken = models.PositiveIntegerField(default=0, verbose_name="عدد الأيام المأخوذة")
    remaining_days = models.IntegerField(null=True, blank=True ,  verbose_name="عدد الأيام المتبقية")  # الأيام المتبقية
    compensation_date = models.DateField(null=True, blank=True, verbose_name="بدل عن ترايخ")


    def save(self, *args, **kwargs):
        if self.start_date and self.end_date:
            self.days_taken = (self.end_date - self.start_date).days + 1  # +1 لحساب اليوم الأول
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.officer.user.username} - {self.get_leave_type_display()}"


class Notification(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.TextField()
    is_read = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    link = models.URLField(blank=True, null=True)  # Add a link field for redirection

    def __str__(self):
        return self.message
    
    
class DailyAttendance(models.Model):
    officer = models.ForeignKey(Officer, on_delete=models.CASCADE, verbose_name="الضابط")
    date = models.DateField(default=timezone.now, verbose_name="التاريخ")
    status = models.ForeignKey(UnitStatus, on_delete=models.SET_NULL, null=True, verbose_name="الحالة اليومية")
    notes = models.TextField(blank=True, null=True, verbose_name="ملاحظات")

    class Meta:
        unique_together = ('officer', 'date')
        verbose_name = 'تمام يومي'
        verbose_name_plural = 'تمامات يومية'

    def __str__(self):
        return f"{self.officer.full_name} - {self.date} - {self.status.name}"  
    
# نوبطجيات 


class ShiftTeam(models.Model):
    TEAM_TYPE_CHOICES = [
        ('قائد منوب', 'قائد منوب'),
        ('ضابط نوبطچي', 'ضابط نوبطچي')
    ]
    team_type = models.CharField(max_length=20, choices=TEAM_TYPE_CHOICES, verbose_name="نوع الطاقم")
    officer = models.ForeignKey(Officer, on_delete=models.CASCADE, related_name='shift_teams', verbose_name="الضابط")
    created_at = models.DateTimeField(auto_now_add=True,verbose_name="تاريخ الإنشاء")


class Shift(models.Model):
    officer = models.ForeignKey(Officer, on_delete=models.CASCADE)
    team = models.ForeignKey(ShiftTeam, on_delete=models.CASCADE)
    start_date = models.DateField()
    end_date = models.DateField()
    is_holiday = models.BooleanField(default=False)


class ShiftSwapRequest(models.Model):
    PENDING = 'pending'
    APPROVED = 'approved'
    REJECTED = 'rejected'
    
    STATUS_CHOICES = [
        (PENDING, 'جـاري التصديــق'),
        (APPROVED, 'تصــدق'),
        (REJECTED, 'لم يتصدق'),
    ]

templates/parts/footer.html
<footer class="app-footer"> 
    <div class="float-end d-none d-sm-inline"> 
        <strong> حقوق الطبع والنشر &copy; 2024-2025 <a href="/about">معهد نظم المعلومات مركز الحاسب</a>.  </strong>
    </div>

    <div class="float-start d-none d-sm-inline-block">
        <a target="_blank" class="text-decoration" href="https://www.isi.com.eg/isisite/Courses.aspx"><i class="fas fa-arrow-up "></i>موقع معهد نظم المعلومات  </a>
        
    </div>
        
</footer>

templates/parts/nav.html
{% load django_bootstrap5 %}
{% load static %}
{% load custom_filters %}
<nav class="app-header navbar navbar-expand bg-body"> 
  <div class="container-fluid"> 
      <ul class="navbar-nav">
  
        <li class="nav-item"> <a class="nav-link" data-lte-toggle="sidebar" href="#" role="button"> <i class="fas fa-bars"></i> </a> </li>
        <li class="nav-item d-none d-sm-inline-block"> <a href="{% url 'home' %}" class="nav-link text-bold">الرئيسية</a> </li>
        
        <li class="nav-item d-flex flex-column justify-content-center">
          <form method="GET" action="{% url 'officers' %}" class="form-inline ml-3">
            <div class="input-group input-group-sm">
              <input class="form-control form-control-navbar" name="search_name" type="search" placeholder="بحث بالاسم" aria-label="Search">
              <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                  <i class="fas fa-search"></i>
                </button>
              </div>
            </div>
          </form>
        </li>
              


      </ul>
      <div>
      <button class="theme-toggle-button" id='darkModeButton'> <i class="fas fa-moon"></i> </button></div>

      
      
      <div class="dropdown-toggle" id="notificationDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        <i class="fas fa-bell"></i>
        <span class="badge bg-danger" id="unreadCount">{{ unread_notifications_count }}</span>
      </div>
    <ul class="dropdown-menu" aria-labelledby="notificationDropdown" id="notificationList">
        {% comment %} {% for notification in request.user.notification_set.all %}
            <li>
                <a id="notification-{{notification.id}}" class="dropdown-item notification-item d-flex" data-id="{{ notification.id }}" data-link="{{ notification.link }}" href="#">
                    {{ notification.message }}
                    <small class="text-muted">{{ notification.created_at|date:"d-m-Y سعت  Hm "|arabic_numbers }}</small>
                </a>
            </li>
        {% empty %}
            <li><a class="dropdown-item" href="#">لا توجد إشعارات</a></li>
        {% endfor %} {% endcomment %}
    </ul>
    
    <audio id="notificationSound" src="{% static "audio/notification.mp3" %}" preload="auto"></audio>
   
    

      <div class="d-flex align-items-center">
        <div class="image me-2">
            {% if request.user.officer_profile.profile_image %}
                <img src="{{ request.user.officer_profile.profile_image.url }}" class="rounded-circle elevation-3" alt="User Image"
                     style="width: 50px; height: 50px; border: 2px solid #007bff; padding: 3px; box-shadow: 0 10px 20px rgba(0, 0, 0, .19), 0 6px 6px rgba(0, 0, 0, .23) !important">
            {% else %}
                <img src="{% static 'images/user-placeholder.png' %}" class="rounded-circle elevation-3" alt="User Image"
                     style="width: 50px; height: 50px; border: 2px solid #007bff; padding: 3px; box-shadow: 0 10px 20px rgba(0, 0, 0, .19), 0 6px 6px rgba(0, 0, 0, .23) !important">
            {% endif %}
        </div>
    
        <div class="info me-auto">
            <span class="text-bold d-block" style="font-size: 14px; color: #6c757d;">المستخدم الآن</span>
            <a href="{% url 'profile_view'%}" class="d-block" style="font-size: 18px; font-weight: bold; color: #007bff; text-decoration: none;">
              {% if request.user.officer_profile %}
                {{ request.user.officer_profile.rank }}/{{ request.user.officer_profile.full_name }}
              {% else %}
                {{request.user.username}}
              {% endif %}
            </a>
        </div>
    </div>
    
    
    <button id="colorChangeButton" class="btn border-0">تشغيل تجريبي</button>

    
    
    <div class="d-flex justify-content-between align-items-center mt-3">
        <!-- Date and Time -->
        <nav class="d-flex flex-column align-items-center me-auto">
            <span id="current-date" style="font-size: 14px; color: #6c757d;"></span>
            <span id="current-time" style="font-size: 14px; color: #6c757d;"></span>
        </nav>
        
        <!-- Logout Button -->
        <form method="post" action="{% url 'logout' %}" class="ms-3">
            {% csrf_token %}
            <button type="submit" class="btn btn-outline-secondary">تسجيل الخروج</button>
        </form>
    </div>
    
    

  </div> 
</nav> 

<script>
document.addEventListener('DOMContentLoaded', (event) => {
  const htmlElement = document.documentElement;

  // assume darkmode initaliity
  const currentTheme = localStorage.getItem('bsTheme') || 'dark';
  htmlElement.setAttribute('data-bs-theme', currentTheme);

  document.getElementById('darkModeButton').addEventListener('click',()=>{
    if ((localStorage.getItem('bsTheme') || 'dark') == 'light') {
          document.documentElement.setAttribute('data-bs-theme', 'dark');
          localStorage.setItem('bsTheme', 'dark');
      } else {
          document.documentElement.setAttribute('data-bs-theme', 'light');
          localStorage.setItem('bsTheme', 'light');
      }
  })

});
</script>

<!-- JavaScript for real-time Arabic Date and Time in 12-hour format -->
<script>
  function updateDateTime() {
    const optionsDate = { weekday: 'long', year: 'numeric', month: 'numeric', day: 'numeric', timeZone: 'Africa/Cairo' };
    const optionsTime = { hour: 'numeric', minute: 'numeric', second: 'numeric', hour12: true, timeZone: 'Africa/Cairo' };
    
    const now = new Date();
    const date = now.toLocaleDateString('ar-EG', optionsDate);
    const time = now.toLocaleTimeString('ar-EG', optionsTime);

    document.getElementById('current-date').textContent = date;
    document.getElementById('current-time').textContent = time;
  }

  // Update date and time every second
  setInterval(updateDateTime, 1000);

  // Initial call to set the time immediately
  updateDateTime();


</script>

<script>
  document.addEventListener('DOMContentLoaded', (event) => {
      const button = document.getElementById('colorChangeButton');
      
      // Colors for the background and text
      let colors = [
          { background: 'black', text: 'white' },
          { background: 'white', text: 'black' }
      ];
      let colorIndex = 0;

      // Function to change color
      function changeColor() {
          button.style.backgroundColor = colors[colorIndex].background;
          button.style.color = colors[colorIndex].text; // Change text color based on background
          colorIndex = (colorIndex + 1) % colors.length; // Cycle through colors
      }

      // Change color every 500 milliseconds
      setInterval(changeColor, 500);
  });
</script>
<script>
    function setNotificationCallbacks(){
      const notificationItems = document.querySelectorAll('.notification-item');
      const unreadCount = document.getElementById('unreadCount');
      const notificationSound = document.getElementById('notificationSound');

      notificationItems.forEach(item => {
          item.addEventListener('click', function(event) {
              event.preventDefault();
              const notificationId = this.getAttribute('data-id');
              const link = this.getAttribute('data-link');
              
  
              // Make an AJAX request to mark the notification as read
              $.ajax({
                  url: "{% url 'mark_notification_read' '0' %}".replace('0', notificationId),
                  method: "POST",
                  data: {
                      'csrfmiddlewaretoken': '{{ csrf_token }}',  // Include CSRF token
                  },
                  success: function(response) {
                      if (response.success) {
                          // Remove the notification from the list
                           // document.getElementById(`notification-${notificationId}`).remove();
                          // this.target.remove();
                          // item.closest('li').remove();
                          // Decrement unread count
                          const currentCount = parseInt(unreadCount.textContent);
                          unreadCount.textContent = currentCount - 1;
                          // Redirect the user to the link based on the notification
                          window.location.href = link;
                      } else {
                          console.error('Failed to mark notification as read:', response.error);
                      }
                  },
                  error: function(xhr, status, error) {
                      console.error('AJAX error:', status, error);
                  }
              });
          });
      });
    }


    function updateNotificationList(cb) {
        $.ajax({
            url: "{% url 'notification_list' %}",  // Use the correct URL for checking new notifications
            method: "GET",
            success: function(response) {
            
            document.getElementById("notificationList").innerHTML = response
            setNotificationCallbacks();
            if (cb) cb();
            }});
    }

  document.addEventListener('DOMContentLoaded', () => {
      // Function to check for new notifications
      let prev_unread_count = 0;
      function checkNewNotifications(isFirstCall) {
          $.ajax({
              url: "{% url 'check_new_notifications' %}",  // Use the correct URL for checking new notifications
              method: "GET",
              success: function(response) {
                if (response.unread_count > 0) {
                    updateNotificationList(()=>{
                            if (!isFirstCall && prev_unread_count !== response.unread_count){
                                notificationSound.play();
                            }
                            unreadCount.textContent = response.unread_count;
                            prev_unread_count = response.unread_count
                    })
                }

              },
              error: function(xhr, status, error) {
                  console.error('Error fetching new notifications:', status, error);
              }
          });
      }
  
       //Check for new notifications every 30 seconds
       updateNotificationList();
       checkNewNotifications(true);
       setInterval(checkNewNotifications, 10000);
  });

  </script>